POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Second blog",
  "author": "Admin",
  "url": "https://test.com/admin",
  "likes": 0,
  "user": "5ee792826a5574525043d398"
}