POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZXQiLCJpZCI6IjVlZjI1YjFjNDcyN2MzNTIzMGI2ZTRhZiIsImlhdCI6MTU5Mjk0MTQwMH0.ZSVrZZGmaktUdj_xTcPmqP3lb6LmqwSDWPeTyLQS6xU

{
  "title": "Fifth blog",
  "author": "Viet Phan",
  "url": "https://test.com/viet55",
  "likes": 0
}